config/routes.rb
Rails.application.routes.draw do
  get 'session/new'

  get 'user/new'

  root 'main#index'

  get "log_out" => "session#destroy", :as => "log_out"
  get "log_in" => "session#new", :as => "log_in"
  get "sign_up" => "user#new", :as => "sign_up"
  get 'online_credit' => 'main#online_credit'

  resources :user
  resources :session
  resource :accounts, :cards
  namespace :operator do
    resources :credits
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    # Handle the case where we don't have a current_user i.e. the user is a guest
    user ||= User.new
    client ||= Client.find_by(user_id: user.id)

    # # Define a few sample abilities
    if user.is? 'client'
      can :read, Card, client_id: client.id
      can :update, Card, client_id: client.id
      can :read, Account, client_id: client.id
      can :update, Account, client_id: client.id
    end

    if user.is? 'operator'
      can :manage, Credit
    end
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  # attr_accessor :id, :account_type, :IBAN, :balance, :currency_id, :client_id, :is_sms,
  #               :is_email, :is_active, :is_deleted
  belongs_to :user
  belongs_to :currency
  has_many :cards
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :user
  belongs_to :account
end

app/models/client.rb
class Client < ActiveRecord::Base

  has_many :cards
  has_many :accounts

  def self.get_client_id_by_user_id(user_id)
    Client.find_by(:user_id => user_id)
  end
end

app/models/credit.rb
class Credit < ActiveRecord::Base
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  has_many :account
end

app/models/role.rb
class Role < ActiveRecord::Base
  self.table_name = 'user_roles'
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role
  bad_attribute_names  :hash

  attr_accessor :password, :error_message
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :name
  validates_uniqueness_of :name


  def self.authenticate(name, password)
    user = find_by_name(name)
    if user && user[:hash] == Digest::MD5.hexdigest(user.salt+password).to_s
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.attributes = {hash:  Digest::MD5.hexdigest(self.salt + password).to_s}
      # self.write_attribute('hash', Digest::MD5.hexdigest(self.salt + password).to_s)
      # self.hash = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def is?( requested_role )
    if self.role
      return self.role.name == requested_role.to_s
    end
    false
  end



end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  load_and_authorize_resource
  def show
    flash[:notice] = nil
    @accounts = current_client.accounts
  end
  def update

    sms_ids = params[:sms_ids]
    emails_ids = params[:emails_ids]

    @accounts = current_client.accounts

    @accounts.each do |account|
      if sms_ids
        if sms_ids.index(account.id.to_s)
          account.is_sms = true
        else
          account.is_sms = false
        end
      else
        account.is_sms = false
      end

      if emails_ids
        if emails_ids.index(account.id.to_s)
          account.is_email = true
        else
          account.is_email = false
        end
      else
        account.is_email = false
      end

      account.save
    end

    flash[:notice] = 'Изменения сохранены'
    render 'accounts/show'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :current_client
  rescue_from CanCan::AccessDenied do | exception |
    redirect_to root_url, alert: exception.message
  end
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def current_client
    @current_client ||= Client.find_by(user_id: @current_user.id)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  load_and_authorize_resource

  def show
    flash[:notice] = nil
    @cards = current_client.cards
    puts json: @cards
  end

  def update

    sms_ids = params[:sms_ids]
    emails_ids = params[:emails_ids]

    @cards = current_client.cards

    @cards.each do |card|
      if sms_ids
        if sms_ids.index(card.id.to_s)
          card.is_sms = true
        else
          card.is_sms = false
        end
      else
        card.is_sms = false
      end

      if emails_ids
        if emails_ids.index(card.id.to_s)
          card.is_email = true
        else
          card.is_email = false
        end
      else
        card.is_email = false
      end

      card.save
    end

    flash[:notice] = 'Изменения сохранены'
    render 'cards/show'
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  end
  def online_credit

  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
  def create
    user = User.authenticate(params[:name], params[:password])
    puts json: user
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Вошли"
    else
      flash[:error] = "Неправильный пароль и логин"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def index
    @cards = Account.all
    render  json: @cards
  end

  def new
    @user = User.new
  end

  def create
    identifical_number = params[:identifical_number]
    password = params[:password]
    password_confirmation = params[:password_confirmation]

    if password != password_confirmation
      flash[:notice] = 'Пароли не совпадают';
    end
    @user =  User.create_client_user_account(identifical_number, password)

    if flash.nil?
      if @user.save
        redirect_to root_url, :notice => "Пользователь зарегистрирован."
      end
    else
      flash.now.alert = @user.error_message
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,  :password, :password_confirmation)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RudeInternetBank</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'shared/header' %>
<%= render partial: 'shared/menu' %>
<%= yield %>
<%= render partial: 'shared/footer' %>

</body>
</html>

app/views/shared/_footer.html.erb
<div id="footer" class="ui inverted vertical segment homepage">
  <div class="ui stackable divided relaxed grid">

    <div class="ten wide column">
      <p>Республика Беларусь, 220123 г. Минск, ул. Кропоткина 96-210.</p>
      <p>УНП 190221536</p>
    </div>

    <div class="six wide column">
      <div class="contacts">
        <p><i class="icon call"></i> <a href="tel:+375444946388">+375 (44) 495-63-88</a></p>
        <p><i class="icon mail"></i> <a href="mailto:info@certificat.by">info@rude-bank.by</a></p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div id="header" class="ui inverted vertical segment">
  <div class="ui stackable divided grid">

    <div class="row">
      <div class="twelve wide column logo">
        <%= image_tag('cash.png')%> <span>Rude Bank</span>
      </div>
    </div>
  </div>
</div>

app/views/shared/_menu.html.erb
<div id="menu" class="ui menu inverted">
  <%= link_to "Главная", root_path, class: 'item' %>
  <%= link_to 'Онлайн заявка на кредит', 'https://still-meadow-1611.herokuapp.com/online_credit/new', class: 'item' %>
  <%= link_to 'Оформление кредита', 'https://still-meadow-1611.herokuapp.com/bank_credit/new', class: 'item' if can? :manage, Credit %>
  <%= link_to 'Одобрение кредита', 'https://still-meadow-1611.herokuapp.com/credit_administrate', class: 'item' if can? :manage, Credit %>

  <% if current_user %>
    <%= link_to 'Счета', accounts_path, class: 'item' if can? :read, Account%>
    <%= link_to 'Карточки', cards_path, class: 'item' if can? :read, Card%>
  <%end%>
  <div class="right menu">
    <% if current_user %>
        <%= link_to "Выход (#{current_user.name})", log_out_path, class: 'item' %>
    <% else %>
        <%= link_to "Войти",  log_in_path, class: 'item'%>
    <% end %>
  </div>
</div>