config/routes.rb
Rails.application.routes.draw do
  get 'session/new'

  get 'user/new'

  root 'main#index'

  get "log_out" => "session#destroy", :as => "log_out"
  get "log_in" => "session#new", :as => "log_in"
  get "sign_up" => "user#new", :as => "sign_up"
  get 'online_credit' => 'main#online_credit'

  resources :user
  resources :session
  resource :accounts, :cards
  namespace :operator do
    resources :credits
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    # Handle the case where we don't have a current_user i.e. the user is a guest
    user ||= User.new
    client ||= Client.find_by(user_id: user.id)

    # # Define a few sample abilities
    if user.is? 'client'
      can :read, Card, client_id: client.id
      can :update, Card, client_id: client.id
      can :read, Account, client_id: client.id
      can :update, Account, client_id: client.id
    end

    if user.is? 'operator'
      can :manage, Credit
    end
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  # attr_accessor :id, :account_type, :IBAN, :balance, :currency_id, :client_id, :is_sms,
  #               :is_email, :is_active, :is_deleted
  belongs_to :user
  belongs_to :currency
  has_many :cards
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :user
  belongs_to :account
end

app/models/client.rb
class Client < ActiveRecord::Base

  has_many :cards
  has_many :accounts

  def self.get_client_id_by_user_id(user_id)
    Client.find_by(:user_id => user_id)
  end
end

app/models/credit.rb
class Credit < ActiveRecord::Base
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  has_many :account
end

app/models/role.rb
class Role < ActiveRecord::Base
  self.table_name = 'user_roles'
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role
  bad_attribute_names  :hash

  attr_accessor :password, :error_message
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :name
  validates_uniqueness_of :name


  def self.authenticate(name, password)
    user = find_by_name(name)
    if user && user[:hash] == Digest::MD5.hexdigest(user.salt+password).to_s
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.attributes = {hash:  Digest::MD5.hexdigest(self.salt + password).to_s}
      # self.write_attribute('hash', Digest::MD5.hexdigest(self.salt + password).to_s)
      # self.hash = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def is?( requested_role )
    if self.role
      return self.role.name == requested_role.to_s
    end
    false
  end



end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  load_and_authorize_resource
  def show
    flash[:notice] = nil
    @accounts = current_client.accounts
  end
  def update

    sms_ids = params[:sms_ids]
    emails_ids = params[:emails_ids]

    @accounts = current_client.accounts

    @accounts.each do |account|
      if sms_ids
        if sms_ids.index(account.id.to_s)
          account.is_sms = true
        else
          account.is_sms = false
        end
      else
        account.is_sms = false
      end

      if emails_ids
        if emails_ids.index(account.id.to_s)
          account.is_email = true
        else
          account.is_email = false
        end
      else
        account.is_email = false
      end

      account.save
    end

    flash[:notice] = 'Изменения сохранены'
    render 'accounts/show'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :current_client
  rescue_from CanCan::AccessDenied do | exception |
    redirect_to root_url, alert: exception.message
  end
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def current_client
    @current_client ||= Client.find_by(user_id: @current_user.id)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  load_and_authorize_resource

  def show
    flash[:notice] = nil
    @cards = current_client.cards
    puts json: @cards
  end

  def update

    sms_ids = params[:sms_ids]
    emails_ids = params[:emails_ids]

    @cards = current_client.cards

    @cards.each do |card|
      if sms_ids
        if sms_ids.index(card.id.to_s)
          card.is_sms = true
        else
          card.is_sms = false
        end
      else
        card.is_sms = false
      end

      if emails_ids
        if emails_ids.index(card.id.to_s)
          card.is_email = true
        else
          card.is_email = false
        end
      else
        card.is_email = false
      end

      card.save
    end

    flash[:notice] = 'Изменения сохранены'
    render 'cards/show'
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  end
  def online_credit

  end
end

app/controllers/operator/credits_controller.rb
module Operator
  class Credits_controller
    def index

    end

  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
  def create
    user = User.authenticate(params[:name], params[:password])
    puts json: user
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Вошли"
    else
      flash[:error] = "Неправильный пароль и логин"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def index
    @cards = Account.all
    render  json: @cards
  end

  def new
    @user = User.new
  end

  def create
    identifical_number = params[:identifical_number]
    password = params[:password]
    password_confirmation = params[:password_confirmation]

    if password != password_confirmation
      flash[:notice] = 'Пароли не совпадают';
    end
    @user =  User.create_client_user_account(identifical_number, password)

    if flash.nil?
      if @user.save
        redirect_to root_url, :notice => "Пользователь зарегистрирован."
      end
    else
      flash.now.alert = @user.error_message
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,  :password, :password_confirmation)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/accounts/show.html.erb
<div id="container">
  <div id="content" class="account-settings">
    <div id="accounts" class="ui segment">
      <%= form_tag accounts_path, method: 'patch' do %>
        <h3 class="ui header dividing">Банковские счета</h3>
          <% unless flash[:notice].nil? %>
              <div class="ui success message">
                <% flash.each do |name, msg| %>
                    <%= content_tag :p, msg %>
                <% end %>

              </div>
          <% end %>
          <% flash[:notice] = nil%>
        <table class="ui table celled striped">
          <thead>
          <tr>
            <th>Наименование</th>
            <th class="center width-10">Доступный остаток</th>
            <th class="center width-5">Валюта</th>
            <!--<th class="center width-10">Последняя операция</th>-->
            <th class="center width-5">Уведомления</th>
          </tr>
          </thead>

          <tbody>
            <% @accounts.each do |account|%>
            <tr>
              <td class="bold"><a href="#"><%= account.IBAN%></a> </td>
              <td class="center"><%= account.balance%></td>
              <td class="center"><%= account.currency.name%></td>
              <td>
                <div class="list">
                  <div class="item">
                    <div class="ui child checkbox">
                      <%= check_box_tag "sms_ids[]", account.id.to_s, account.is_sms%>
                      <label>SMS</label>
                    </div>
                  </div>
                  <div class="item">
                    <div class="ui child checkbox">
                      <%= check_box_tag "emails_ids[]", account.id.to_s, account.is_email%>
                      <label>Email</label>
                    </div>
                  </div>
                </div>
              </td>
            </tr>
          <%end%>

          </tbody>
        </table>
        <div class="buttons">
          <button class="ui button">Сохранить изменения</button>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/cards/show.html.erb
<div id="container">
  <div id="content" class="account-settings">

    <div id="cards" class="ui segment">
      <%=form_tag cards_path, method: 'patch' do%>
        <h3 class="ui header dividing">Пластиковые карты</h3>
          <% unless flash[:notice].nil? %>
              <div class="ui success message">
                <% flash.each do |name, msg| %>
                    <%= content_tag :p, msg %>
                <% end %>

              </div>
          <% end %>
          <% flash[:notice] = nil%>
        <table class="ui table celled striped">
          <thead>
          <tr>
            <th>Класс карты</th>
            <th>Тип карты</th>
            <th>Номер карты</th>
            <th>Привязанный счёт</th>
            <th class="center width-10">Доступный остаток</th>
            <th class="center width-5">Валюта</th>
            <!--<th class="center width-10">Последняя операция</th>-->
            <th class="center width-5">Уведомления</th>
          </tr>
          </thead>

          <tbody>
          <% @cards.each do |card|%>
            <% if can? :read, card %>
                <tr>
                  <td class="bold"><%=card.card_type%></td>
                  <td class="bold"><%=card.account.account_type%></td>
                  <td class="bold"><a href="#"><%=card.number%></a></td>
                  <td class="bold"><a href="#"><%=card.account.IBAN%></a></td>
                  <td class="center"><%=card.account.balance%></td>
                  <td class="center"><%= card.account.currency.name%></td>
                  <td>
                    <div class="list">
                      <div class="item">
                        <div class="ui child checkbox">
                          <%= check_box_tag "sms_ids[]", card.id.to_s, card.is_sms%>
                          <label>SMS</label>
                        </div>
                      </div>
                      <div class="item">
                        <div class="ui child checkbox">
                          <%= check_box_tag "emails_ids[]", card.id.to_s, card.is_email%>
                          <label>Email</label>
                        </div>
                      </div>
                    </div>
                  </td>
                </tr>
            <%end%>
          <%end%>

          </tbody>
        </table>

        <div class="buttons">
          <button class="ui button">Сохранить изменения</button>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/main/index.html.erb
<div id="container">
  <div id="content" >
    <div class="ui cards centered four">
      <div class="card">
        <div class="content">
          <%= image_tag('safe.png')%>

          <div class="description">

            <b>Депозиты.</b> Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Nulla mi enim, accumsan non molestie vel, tincidunt sit amet augue.
            Nulla et malesuada lorem, a rutrum nibh. Etiam et dictum elit.
            Etiam aliquam sollicitudin mi, in maximus enim aliquet et.
            Mauris malesuada purus vitae tellus rutrum, non malesuada velit facilisis. Aliquam vel lectus luctus dui molestie hendrerit. Aliquam convallis ultricies arcu venenatis venenatis.
          </div>
        </div>

        <div class="ui bottom attached button">
          <i class="add icon"></i>
          Узнать больше
        </div>
      </div>

      <div class="card">
        <div class="content">
          <%= image_tag('credit-card.png')%>

          <div class="description">

            <b>Кредитные линии.</b> Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Nulla mi enim, accumsan non molestie vel, tincidunt sit amet augue.
            Nulla et malesuada lorem, a rutrum nibh. Etiam et dictum elit.
            Etiam aliquam sollicitudin mi, in maximus enim aliquet et.
            Mauris malesuada purus vitae tellus rutrum, non malesuada velit facilisis. Aliquam vel lectus luctus dui molestie hendrerit. Aliquam convallis ultricies arcu venenatis venenatis.
          </div>
        </div>

        <div class="ui bottom attached button">
          <i class="add icon"></i>
          Узнать больше
        </div>
      </div>

      <div class="card">
        <div class="content">
          <%= image_tag('email.png')%>

          <div class="description">

            <b>Email уведомления.</b> Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Nulla mi enim, accumsan non molestie vel, tincidunt sit amet augue.
            Nulla et malesuada lorem, a rutrum nibh. Etiam et dictum elit.
            Etiam aliquam sollicitudin mi, in maximus enim aliquet et.
            Mauris malesuada purus vitae tellus rutrum, non malesuada velit facilisis. Aliquam vel lectus luctus dui molestie hendrerit. Aliquam convallis ultricies arcu venenatis venenatis.
          </div>
        </div>

        <div class="ui bottom attached button">
          <i class="add icon"></i>
          Узнать больше
        </div>
      </div>

      <div class="card">
        <div class="content">
          <%= image_tag('sms.png')%>
          <div class="description">

            <b>SMS уведомления.</b> Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Nulla mi enim, accumsan non molestie vel, tincidunt sit amet augue.
            Nulla et malesuada lorem, a rutrum nibh. Etiam et dictum elit.
            Etiam aliquam sollicitudin mi, in maximus enim aliquet et.
            Mauris malesuada purus vitae tellus rutrum, non malesuada velit facilisis. Aliquam vel lectus luctus dui molestie hendrerit. Aliquam convallis ultricies arcu venenatis venenatis.
          </div>
        </div>

        <div class="ui bottom attached button">
          <i class="add icon"></i>
          Узнать больше
        </div>
      </div>

      <div class="card">
        <div class="content">
          <%= image_tag('support.png')%>

          <div class="description">

            <b>Техническая поддержка.</b> Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Nulla mi enim, accumsan non molestie vel, tincidunt sit amet augue.
            Nulla et malesuada lorem, a rutrum nibh. Etiam et dictum elit.
            Etiam aliquam sollicitudin mi, in maximus enim aliquet et.
            Mauris malesuada purus vitae tellus rutrum, non malesuada velit facilisis. Aliquam vel lectus luctus dui molestie hendrerit. Aliquam convallis ultricies arcu venenatis venenatis.
          </div>
        </div>

        <div class="ui bottom attached button">
          <i class="add icon"></i>
          Узнать больше
        </div>
      </div>

      <div class="card">
        <div class="content">
          <%= image_tag('cloud.png')%>

          <div class="description">

            <b>Интернет-банкинг.</b> Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Nulla mi enim, accumsan non molestie vel, tincidunt sit amet augue.
            Nulla et malesuada lorem, a rutrum nibh. Etiam et dictum elit.
            Etiam aliquam sollicitudin mi, in maximus enim aliquet et.
            Mauris malesuada purus vitae tellus rutrum, non malesuada velit facilisis. Aliquam vel lectus luctus dui molestie hendrerit. Aliquam convallis ultricies arcu venenatis venenatis.
          </div>
        </div>

        <div class="ui bottom attached button">
          <i class="add icon"></i>
          Узнать больше
        </div>
      </div>

      <div class="card">
        <div class="content">
          <%= image_tag('test.png')%>
          <div class="description">

            <b>Онлайн заявка на кредит.</b> Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Nulla mi enim, accumsan non molestie vel, tincidunt sit amet augue.
            Nulla et malesuada lorem, a rutrum nibh. Etiam et dictum elit.
            Etiam aliquam sollicitudin mi, in maximus enim aliquet et.
            Mauris malesuada purus vitae tellus rutrum, non malesuada velit facilisis. Aliquam vel lectus luctus dui molestie hendrerit. Aliquam convallis ultricies arcu venenatis venenatis.
          </div>
        </div>

        <div class="ui bottom attached button">
          <i class="add icon"></i>
          Узнать больше
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(function()
  {
    window.onresize = function()
    {
      rude.cards.init();
    };

    rude.cards.init();
  });
</script>

app/views/main/online_credit.html.erb
<%= render partial: 'shared/header' %>

<%= render partial: 'shared/menu' %>
<div id="container">
  <div id="content">

    <iframe src="http://localhost:3001/online_credit/new#container" >
    </iframe>

  </div>
</div>
<%= render partial: 'shared/footer' %>

app/views/session/new.html.erb
<div id="container">
  <div id="content">
    <div id="auth" class="ui segment">
      <%= form_tag session_index_path, class: 'ui error form' do %>
          <% unless flash[:error].nil? %>
              <div class="ui error message">
                <%= content_tag :div, 'Наличие ошибок', class: 'header' %>
                <% flash.each do |name, msg| %>
                    <%= content_tag :p, msg %>
                <% end %>
              </div>
          <% end %>
          <div class="field">
            <%= label_tag 'name', 'Логин' %>
            <%= text_field_tag :name, params[:name], placeholder: "Ваш логин" %>
          </div>

          <div class="field">
            <%= label_tag 'password', 'Пароль' %>
            <%= password_field_tag :password, '', placeholder: 'Ваш пароль' %>
          </div>
          <%= button_tag "Авторизация", class: "ui button right" %>
      <% end %>
    </div>

  </div>
</div>

app/views/user/new.html.erb
<%= render partial: 'shared/header' %>

<%= render partial: 'shared/menu' %>
<div id="container">
  <div id="content">

    <div id="auth" class="ui segment">
      <%= form_tag  user_index_path, class: 'ui error form' do %>
          <%if flash.nil? %>
            <div class="ui error message">
              <%= content_tag :div, 'Наличие ошибок', class:'header' %>
              <% flash.each do |name, msg| %>
                  <%= content_tag :p, msg%>
              <% end %>
            </div>
          <%end%>
          <div class="field">
            <%= label_tag 'identifical_number', 'Индетификационный номер' %><br />
            <%= text_field_tag :identifical_number, params[:identifical_number] %>
          </div>
          <div class="field">
            <%= label_tag 'password', 'Пароль' %><br />
            <%= password_field_tag :password %>
          </div>
          <div class="field">
            <%= label_tag 'password_confirmation','Подтвердите пароль' %><br />
            <%= password_field_tag :password_confirmation %>
          </div>
          <%= button_tag "Зарегистрироваться", class:"ui button right"  %>
      <% end %>
      <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
    </div>

  </div>
</div>
<%= render partial: 'shared/footer' %>